name: build
on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 6
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@master
    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      shell: bash -l {0}
      run: |
          conda install --yes -c conda-forge -c alubbock numpy scipy nose cython pysb
    - name: Install PyDREAM
      shell: bash -l {0}
      run: |
        python -m pip install .
    - name: Run nosetests
      run: 30 nosetests
